name: curator build push

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
  create:
    tags:
      - v*

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: azure/docker-login@v1
        with:
<<<<<<< HEAD
          login-server: "bulatacr.azurecr.io"
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Set up Docker Buildx
=======
          login-server: 'bulatacr.azurecr.io'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
>>>>>>> b2a411f80713507224d969216aa2c623aa2ab3cd
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile 
          push: true
          tags: bulatacr.azurecr.io/elk-curator:${{github.ref_name}}
