name: curator build push

on:
  create:
    tags:
      - v*

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: azure/docker-login@v1
        with:
          login-server: "bulatacr.azurecr.io"
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile 
          push: true
          tags: bulatacr.azurecr.io/elk-curator:${{github.ref_name}}
